### PR TITLE
Comment wasn't right for purging ETAs from data in sim_ipred

### PR DESCRIPTION
**Pull request by kylebaron**
See #120

### CODE REVIEW

**Comment by kylebaron** [comment]
I had the wrong base for this. Will re-do and push.

**Comment by kyleam** [comment]
Thanks; assuming you're targeting `refactor/etasrc`, feel free to just push it there.

**Comment by kylebaron** [comment]
I think I had it right the first time; the comment is already in `main` so I made the PR against that branch.

**Comment by kyleam** [comment]
> I think I had it right the first time; the comment is already in `main` so I made the PR against that branch.

Works for me; thanks

**Pull request closed without merging**
