### PR TITLE
nmbayes: add custom methods for tailored errors

### PR DESCRIPTION
**Pull request by kyleam**
On nmbayes models, cov_cor() and nm_file() fail with messages about not being able to find the expected files in the top-level directory. Neither of these map simply onto the nmbayes submodel structure. Define custom methods to get slightly more informative errors (at least until we have a clearer vision of something that either of these should do).

Re: #36

### CODE REVIEW

**Comment by seth127** [comment]
@kyleam what do you think about creating a `build_path_from_model.bbi_nmbayes_model` method that acts as it does now, but messages something like "`build_path_from_model()` does not build paths to files in chain directories. Consider using `chain_paths()` instead."?

Given the all of the nuance captured in https://github.com/metrumresearchgroup/bbr/issues/618, I don't think we're ready to implement a _real_ method for that, but users might find a message like that helpful. Or do you think it's more likely to just be noisy and annoy people?

**Comment by kyleam** [comment]
I said:

> Example output:

Bah, I meant to post that in gh-127

**Review by seth127 — APPROVED** [review]
These changes look good and I'm fine moving ahead with whichever way @kyleam prefers, regarding my `build_path_from_model()` idea in the previous comment.

**Comment by kyleam** [comment]
`build_path_from_model` method with message pointing to `chain_paths` added with faa3859.

**Comment by kyleam** [comment]
> `build_path_from_model` method with message pointing to `chain_paths` added with [faa3859](https://github.com/metrumresearchgroup/bbr.bayes/commit/faa3859616c236748eb05500d2e50f0cdb863eeb).

Will merge now, but @seth127 if you take a look at the new method and have any comments, please let me know.

**Pull request merged**
